# Generated by Django 3.1.1 on 2020-09-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='quant',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
