# Generated by Django 3.1.1 on 2020-09-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_todo_quant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Wacky',
        ),
    ]
